name-template: Channel Mixer v$RESOLVED_VERSION 💚

tag-template: v$RESOLVED_VERSION

categories:
  - title: 🚀 Features
    labels:
      - "bump:minor"
      - feat

  - title: 🐛 Bug Fixes
    labels:
      - "bump:patch"
      - fix

  - title: 🧰 Maintenance
    labels:
      - "bump:major"
      - chore

  - title: ⚡ Performance Improvements
    labels:
      - perf

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - "bump:major"
  minor:
    labels:
      - "bump:minor"
  patch:
    labels:
      - "bump:patch"
  default: patch

template: |
  ## Changes

  $CHANGES
