name: Auto Approve Bump PRs

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Approve Pull Request
        if: github.actor == "GitHub <noreply@github.com>"
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.pull_request.outputs.pull-request-number }}